### ISSUE TITLE
GitHub pages are hosted on github.io

### ISSUE THREAD

**Issue by fodinabor** [UK-MAC/uk-mac.github.com#1]
Hi, on the hosted websites some links are dead since the GitHub page is actually hosted on uk-mac.github.io instead of the .com variant.
E.g. the main page links to https://uk-mac.github.com/CloverLeaf/ instead of https://uk-mac.github.io/CloverLeaf/

**Comment by EdmundGoodman** [comment]
Resolved by #2 (a project maintainer should be able to close this issue)

**Comment by fodinabor** [comment]
Yay :)
